export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";
export const GET_ANSWERED_QUESTIONS = "GET_ANSWERED_QUESTIONS";
export const GET_UNANSWERED_QUESTIONS = "GET_UNANSWERED_QUESTIONS";
export const DELETE_ALL_QUESTIONS = "DELETE_ALL_QUESTIONS";
export const ADD_NEW_POLL = "ADD_NEW_POLL";
